# Generated by Django 4.0.5 on 2022-06-10 20:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RentalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(default=main.validators.month)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('director', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=8)),
                ('duration', models.IntegerField(default=0)),
                ('rentaloffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rentaloffice')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('band', models.CharField(max_length=16)),
                ('genre', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=32)),
                ('duration', models.IntegerField(default=0)),
                ('songslist', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
                ('rentaloffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rentaloffice')),
            ],
            options={
                'unique_together': {('songslist', 'genre')},
            },
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('author', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=8)),
                ('ISBN', models.CharField(max_length=13, unique=True, validators=[main.validators.validate_digit_length])),
                ('rentaloffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rentaloffice')),
            ],
            options={
                'unique_together': {('author', 'title', 'genre')},
            },
            bases=('main.item',),
        ),
    ]
